apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs07
  namespace: nodejs07
  labels:
    app: nodejs07
    environment: production
  annotations:
    argocd-image-updater.argoproj.io/image-list: nodejs07=ghcr.io/quancv2k4/nodejs_tesst
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/write-back-target: apps/nodejs07/deployment.yaml
    argocd-image-updater.argoproj.io/nodejs07.update-strategy: latest
    argocd-image-updater.argoproj.io/nodejs07.allow-tags: regexp:^.*$
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nodejs07
  template:
    metadata:
      labels:
        app: nodejs07
        environment: production
      annotations:
        timestamp: "1762163723"
    spec:
      initContainers:
      - name: init-data-dir
        image: busybox:latest
        command: ['sh', '-c', 'mkdir -p /app/data && chmod 777 /app/data']
        volumeMounts:
        - name: nodejs07-data
          mountPath: /app/data
      containers:
      - name: nodejs07
        image: ghcr.io/quancv2k4/nodejs_tesst:latest
        command: ["/bin/sh", "-c"]
        args:
          - |
            node server
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: production
        - name: ENVIRONMENT
          value: production
        volumeMounts:
        - name: nodejs07-data
          mountPath: /app/data
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: nodejs07-data
        persistentVolumeClaim:
          claimName: nodejs07-pvc
